Repository helm/chart-testing, pull requests merged in 2018-12, with the labels that each got.

#65 Fix typos
  pkg/chart/chart.go
Labels: size/XS

#59 Support installation to existing namespace
  app/cmd/install.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
  pkg/tool/helm.go
  pkg/tool/kubectl.go
Labels: size/L

#66 Lint values files in ci directory
  pkg/chart/chart.go
Labels: size/S

#69 Truncate names to 63 characters
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/M

#68 Add new flags to disable lint/schema validation
  Gopkg.lock
  app/cmd/lint.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/chart/testdata/test_lints/Chart.yaml
  pkg/chart/testdata/test_lints/values.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
Labels: size/L
