Repository helm/chart-testing, pull requests merged in 2018-11, with the labels that each got.

#41 Ensure yamllint is updated to 1.12.1
  Dockerfile
Labels: size/XS

#40 Ensure yq is updated to 2.7.0
  Dockerfile
Labels: size/XS

#39 Ensure helm is updated to v2.11.0
  Dockerfile
Labels: size/XS

#38 Ensure kubectl is updated to v1.12.2
  Dockerfile
Labels: size/XS

#37 Ensure Dockerfile uses more modern pip verison, freeze it to 18.1
  Dockerfile
Labels: size/XS

#35 Re-write it in Go
  .circleci/config.yml
  .dockerignore
  .editorconfig
  .gitignore
  .goreleaser.yml
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  README.md
  app/cmd/docGen.go
  app/cmd/install.go
  app/cmd/lint.go
  app/cmd/lintAndInstall.go
  app/cmd/root.go
  app/cmd/version.go
  app/main.go
  build.sh
  chart_test.sh
  code-of-conduct.md
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_version.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/gke/my_test.sh
  lib/chartlib.sh
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/chart/testdata/empty_maintainers/Chart.yaml
  pkg/chart/testdata/invalid_maintainers/Chart.yaml
  pkg/chart/testdata/no_maintainers/Chart.yaml
  pkg/chart/testdata/no_maintainers_deprecated/Chart.yaml
  pkg/chart/testdata/valid_maintainers/Chart.yaml
  pkg/chart/testdata/valid_maintainers_deprecated/Chart.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
  pkg/exec/exec.go
  pkg/tool/account.go
  pkg/tool/account_test.go
  pkg/tool/git.go
  pkg/tool/helm.go
  pkg/tool/kubectl.go
  pkg/tool/linter.go
  pkg/util/util.go
  pkg/util/util_test.go
  tag.sh
Labels: size/XXL

#44 Update readme
  README.md
Labels: size/S

#47 Document supported versions, upgrading, and version-specific PRs
  README.md
Labels: size/S

#49 Helm code of conduct
  code-of-conduct.md
Labels: size/XS

#50 Bind debug flag to Viper
  app/cmd/root.go
Labels: size/XS

#55 Fixes validate maintainers bug inside chart.Testing.LintChart
  pkg/chart/chart.go
  pkg/chart/chart_test.go
Labels: size/M

#57 Fix readiness check
  pkg/tool/helm.go
Labels: size/XS

#58 Update base images in samples
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
Labels: size/XS

#61 Add kind example
  examples/kind/.circleci/config.yml
  examples/kind/README.md
  examples/kind/test/ct.yaml
  examples/kind/test/e2e-kind.sh
Labels: size/L

#52 Add github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/M
