Repository helm/chart-testing, pull requests merged in 2019-01, with the labels that each got.

#73 Fix index out of range when files exist in the root of a chart dir
  pkg/chart/chart.go
  pkg/chart/chart_test.go
Labels: size/XS

#67 Add support for providing credentials when adding chart-repositories
  README.md
  app/cmd/root.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
  pkg/tool/helm.go
Labels: size/L

#76 Update Goreleaser
  .circleci/config.yml
  .goreleaser.yml
  Dockerfile
Labels: size/S

#75 Update tools
  Dockerfile
Labels: size/XS

#77 Prepare release v2.1.0
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
Labels: size/XS

#80 Fix kind example
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/XS

#81 set port in .kube/config file to 6433
  examples/kind/test/e2e-kind.sh
Labels: size/XS

#82 --chart-repos help message improvement
  app/cmd/root.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_version.md
Labels: size/M

#86 Use anonymous function to avoid defer in loop
  pkg/chart/chart.go
Labels: size/M

#85 Fix regression in changed chart detection
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/util/util.go
Labels: size/M

#87 Only require validation configs when validation is enabled
  pkg/config/config.go
Labels: size/XS

#88 Upgrade Helm to 2.12.2
  Dockerfile
Labels: size/XS

#90 Require charts to be in direct subdirectories of configured charts dirs
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/chart/some_non_chart_dir/some_non_chart_file
  pkg/chart/some_non_chart_file
  pkg/chart/test_chart_at_root/Chart.yaml
  pkg/chart/test_chart_at_root/templates/foo.yaml
  pkg/chart/test_charts/bar/Chart.yaml
  pkg/chart/test_charts/bar/bar_sub/Chart.yaml
  pkg/chart/test_charts/bar/bar_sub/templates/bar_sub.yaml
  pkg/chart/test_charts/foo/Chart.yaml
  pkg/util/util.go
Labels: size/M

#91 Improve error logging
  app/cmd/install.go
  app/cmd/lint.go
  app/cmd/lintAndInstall.go
  pkg/chart/chart.go
  pkg/tool/git.go
Labels: size/S

#94 Update kind example
  examples/kind/.circleci/config.yml
  examples/kind/README.md
  examples/kind/test/ct.yaml
  examples/kind/test/e2e-kind.sh
  examples/kind/test/kind-config.yaml
Labels: size/L

#96 Log values files used
  pkg/chart/chart.go
Labels: size/XS

#97 Upgrade Helm and kubectl in Docker image
  Dockerfile
Labels: size/XS
