Repository helm/chart-testing, pull requests merged in 2019-04, with the labels that each got.

#141 update docker image to use helm 2.13.1
  Dockerfile
Labels: size/XS

#143 Trim leading hyphens from names
  pkg/chart/chart.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/M

#144 Fix kind timeout
  .circleci/config.yml
  e2e-kind.sh
  examples/kind/test/e2e-kind.sh
Labels: size/S

#146 Update golang on circleci (#146)Update golang on circleci
  .circleci/config.yml
  Dockerfile
Labels: size/XS

#148 Update readme and examples for v2.3.1 release
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S

#149 Prepare release v2.3.2
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S

#150 Remove force delete of pv and improve cleanup logic
  pkg/tool/kubectl.go
Labels: size/M

#151 Trim leading invalid chars from names
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/S

#152 Fix log messages
  pkg/chart/chart.go
  pkg/tool/git.go
Labels: size/XS

#153 Use latest upstream instead of local branch for tags
  tag.sh
Labels: size/XS

#154 Prepare release v2.3.3
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S
