Repository helm/chart-testing, pull requests merged in 2019-12, with the labels that each got.

#190 List changed fixes
  pkg/chart/chart.go
  pkg/util/util.go
Labels: size/XS

#194 Update docs for Helm 3
  README.md
  ct/cmd/install.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  doc/ct_version.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
  pkg/chart/chart.go
Labels: size/M

#195 Prepare release v3.0.0-beta.1
  .circleci/config.yml
  Dockerfile
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S
