Repository helm/chart-testing, pull requests merged in 2019-03, with the labels that each got.

#107 Add gofmt to CircleCI
  .circleci/config.yml
  ct/cmd/lint.go
Labels: size/XS

#105 Add GoReportCard badge to README
  README.md
Labels: size/XS

#116 Update kind cluster example with working local storage for all nodes
  examples/kind/test/e2e-kind.sh
  examples/kind/test/local-path-provisioner.yaml
Labels: size/L

#112 force the namespace deletion by updating the finalizers in the namespace obj
  Gopkg.lock
  Gopkg.toml
  pkg/exec/exec.go
  pkg/tool/kubectl.go
  pkg/util/util.go
Labels: size/L

#122 Fix gofmt errors
  pkg/util/util.go
Labels: size/XS

#121 Fix goreleaser docker.binary deprecation notice
  .circleci/config.yml
  .goreleaser.yml
Labels: size/XS

#126 Readme update: lint-changed>list-changed
  README.md
Labels: size/XS

#127 Add badges for build status and license
  README.md
Labels: size/XS

#103 Test chart upgrades
  Gopkg.lock
  ct/cmd/install.go
  ct/cmd/listChanged.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
  pkg/tool/git.go
  pkg/tool/helm.go
  pkg/tool/kubectl.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/L

#128 Update local-path-provisioner
  examples/kind/test/local-path-provisioner.yaml
Labels: size/XS

#104 Handle empty chart path, add Chart type
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/util/util.go
Labels: size/L

#120 Add Helm/Kubernetes integration tests
  .circleci/config.yml
  e2e-kind.sh
  pkg/chart/chart_test.go
  pkg/chart/integration_test.go
  pkg/chart/test_charts/must-pass-upgrade-install/Chart.yaml
  pkg/chart/test_charts/must-pass-upgrade-install/README.md
  pkg/chart/test_charts/must-pass-upgrade-install/ci/test-values.yaml
  pkg/chart/test_charts/must-pass-upgrade-install/templates/_helpers.tpl
  pkg/chart/test_charts/must-pass-upgrade-install/templates/deployment.yaml
  pkg/chart/test_charts/must-pass-upgrade-install/templates/service.yaml
  pkg/chart/test_charts/must-pass-upgrade-install/templates/tests/test-connection.yaml
  pkg/chart/test_charts/must-pass-upgrade-install/values.yaml
  pkg/chart/test_charts/mutating-deployment-selector/Chart.yaml
  pkg/chart/test_charts/mutating-deployment-selector/README.md
  pkg/chart/test_charts/mutating-deployment-selector/templates/_helpers.tpl
  pkg/chart/test_charts/mutating-deployment-selector/templates/deployment.yaml
  pkg/chart/test_charts/mutating-deployment-selector/templates/service.yaml
  pkg/chart/test_charts/mutating-deployment-selector/templates/tests/test-connection.yaml
  pkg/chart/test_charts/mutating-deployment-selector/values.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/Chart.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/README.md
  pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/_helpers.tpl
  pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/service.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/statefulset.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/tests/test-connection.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/values.yaml
Labels: size/XL

#132 Add option to skip upgrade testing of deleted/renamed values files
  ct/cmd/install.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
Labels: size/L

#135 Update kind to v0.2.0
  e2e-kind.sh
  examples/docker-for-mac/my_test.sh
  examples/kind/README.md
  examples/kind/test/e2e-kind.sh
  examples/kind/test/kind-config.yaml
Labels: size/S

#137 fix(account): handle invalid repository domain matches
  pkg/tool/account.go
  pkg/tool/account_test.go
Labels: size/M

#133 Add git version documentation, rename worktree methods, and handle existing worktree
  README.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/tool/git.go
Labels: size/M
