Repository helm/chart-testing, pull requests merged in 2019-11, with the labels that each got.

#180 Prepare release v2.4.0
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S

#183 Migrate to Go modules
  .circleci/config.yml
  .goreleaser.yml
  Gopkg.lock
  Gopkg.toml
  README.md
  build.sh
  ct/cmd/docGen.go
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/lintAndInstall.go
  ct/cmd/listChanged.go
  ct/cmd/version.go
  ct/main.go
  go.mod
  go.sum
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/chart/integration_test.go
  pkg/config/config.go
  pkg/exec/exec.go
  pkg/tool/git.go
  pkg/tool/helm.go
  pkg/tool/kubectl.go
  pkg/tool/linter.go
Labels: size/XL

#187 Bump helm to v2.16.1
  Dockerfile
Labels: size/XS

#184 Add support for Helm 3
  .circleci/config.yml
  Dockerfile
  build.sh
  ct/cmd/docGen.go
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/lintAndInstall.go
  ct/cmd/listChanged.go
  e2e-kind.sh
  go.sum
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/chart/integration_test.go
  pkg/tool/helm.go
  pkg/tool/kubectl.go
Labels: size/L
