Repository helm/chart-testing, pull requests merged in 2020-09, with the labels that each got.

#266 chore: Upgrade to helm 3.3.1
  Dockerfile
Labels: size/XS

#268 Bump versions
  Dockerfile
Labels: size/XS

#269 Add flag for disabling config printing
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/root.go
  pkg/config/config.go
Labels: size/S

#274 Update docs
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
Labels: size/S

#275 Update docs and examples for v3.1.0
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S

#277 Print config to stderr
  ct/cmd/lintAndInstall.go
  ct/cmd/listChanged.go
  ct/cmd/root.go
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  pkg/config/config.go
  pkg/util/util.go
Labels: size/M

#278 Update docs and examples for v3.1.1
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S
