Repository helm/chart-testing, pull requests merged in 2020-10, with the labels that each got.

#281 Add reference to charts-repo-actions-demo
  README.md
Labels: size/XS

#283 Support execution of additional commands during ct lint
  Dockerfile
  ct/cmd/lint.go
  go.mod
  go.sum
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/config/config.go
  pkg/tool/cmdexecutor.go
  pkg/tool/cmdexecutor_test.go
Labels: size/L

#284 Fix typo
  pkg/chart/chart.go
Labels: size/XS

#289 Update Helm to 3.4.0
  Dockerfile
Labels: size/XS

#280 Add option to exclude deprecated charts
  ct/cmd/root.go
  pkg/chart/chart.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
Labels: size/S

#287 Remove redundant "default" descriptions from help output
  ct/cmd/lint.go
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
Labels: size/S

#290 Log invalid chart dirs to stderr
  pkg/chart/chart.go
Labels: size/XS
