Repository helm/chart-testing, pull requests merged in 2020-02, with the labels that each got.

#206 Update kind, Helm, and Go
  .circleci/config.yml
  e2e-kind.sh
  examples/kind/test/e2e-kind.sh
Labels: size/M

#201 examples/kind: Add timeout unit in config
  examples/kind/test/ct.yaml
Labels: size/XS

#205 Don't create provided namespace
  pkg/chart/chart.go
  pkg/chart/integration_test.go
  pkg/chart/test_charts/mutating-deployment-selector/templates/deployment.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/service.yaml
  pkg/chart/test_charts/mutating-sfs-volumeclaim/templates/statefulset.yaml
Labels: size/S

#207 Update Helm to v3.1.1
  .circleci/config.yml
  Dockerfile
Labels: size/XS

#208 Prepare release v3.0.0-beta.2
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/XS
