Repository helm/chart-testing, pull requests merged in 2020-11, with the labels that each got.

#292 Consistently use filepath package
  pkg/config/config.go
  pkg/util/util.go
Labels: size/S

#291 Introduce environment variable for custom config dir
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/default/test.yaml
  pkg/config/testdata/env/test.yaml
Labels: size/M

#297 Move to gh-actions
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  README.md
  tag.sh
Labels: size/L

#303 Update helm to resolve https://github.com/helm/helm/commit/fe23c09552…
  Dockerfile
Labels: size/XS

#304 Bump versions
  Dockerfile
Labels: size/XS
