Repository helm/chart-testing, pull requests merged in 2020-08, with the labels that each got.

#250 Bump docker image helm verison to 3.2.4
  Dockerfile
Labels: size/XS

#252 Add type field to chart schema
  etc/chart_schema.yaml
Labels: size/XS

#253 Bump docker image versions
  Dockerfile
Labels: size/S

#245 cherry-pick #229 into dev-v2
  ct/cmd/root.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/config/config.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
Labels: size/S

#233 Update Helm to 2.16.9
  Dockerfile
Labels: size/S

#255 Deprecate Gopkg and convert to go mod
  .circleci/config.yml
  .goreleaser.yml
  Gopkg.lock
  Gopkg.toml
  build.sh
  ct/cmd/docGen.go
  ct/cmd/version.go
  e2e-kind.sh
  go.mod
  go.sum
  pkg/exec/exec.go
  setup.sh
Labels: size/XL

#259 Bump helm , kubectl versions
  .circleci/config.yml
  Dockerfile
Labels: size/XS

#260 Make home URL optional and support dependencies
  etc/chart_schema.yaml
Labels: size/S

#262 Fix int to string conversion
  pkg/util/util_test.go
Labels: size/XS

#247 Migrate chart-testing formula to homebrew/core
  .goreleaser.yml
  README.md
Labels: size/S
