Repository helm/chart-testing, pull requests merged in 2020-03, with the labels that each got.

#215 Fix ldflags for version
  .goreleaser.yml
Labels: size/XS

#218 Fix printing test results on error
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/lintAndInstall.go
  ct/cmd/root.go
Labels: size/S

#219 Update build, dependencies, Go and tool versions
  .circleci/config.yml
  .goreleaser.yml
  Dockerfile
  ct/cmd/docGen.go
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/lintAndInstall.go
  ct/cmd/listChanged.go
  go.mod
  go.sum
  setup.sh
  tools/tools.go
Labels: size/XL

#222 Adding the apiVersion as a required field in the Chart.yaml validation
  etc/chart_schema.yaml
Labels: size/XS
