Repository helm/chart-testing, pull requests merged in 2022-01, with the labels that each got.

#369 Bump goreleaser to v1.1.0
  go.mod
  go.sum
Labels: size/M

#372 Make description optional in chart_schema
  etc/chart_schema.yaml
Labels: size/XS

#375 Update golang to 1.17 and some goreleaser/docker file updates
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  Dockerfile
  README.md
  go.mod
  go.sum
  pkg/chart/integration_test.go
  setup.sh
  tools/tools.go
Labels: size/XXL
