Repository helm/chart-testing, pull requests merged in 2022-09, with the labels that each got.

#460 Upgrade go1.19, helm update and add golangci-lint job
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/lintAndInstall.go
  ct/cmd/listChanged.go
  e2e-kind.sh
  go.mod
  go.sum
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/chart/integration_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/exec/exec.go
  pkg/tool/account.go
  pkg/tool/account_test.go
  pkg/tool/cmdexecutor_test.go
  pkg/tool/git.go
  pkg/tool/helm.go
  pkg/tool/kubectl.go
  pkg/util/util.go
Labels: size/L

#473 add job to check if docs are up to date
  .github/workflows/ci.yaml
  .gitignore
  ct/cmd/root.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  doc/ct_version.md
Labels: size/M

#474 fix: using helm version --short resulting in an invalid semantic versioning
  pkg/tool/helm.go
Labels: size/XS

#472 Add config option to disable printing of container logs
  pkg/chart/chart.go
  pkg/config/config.go
Labels: size/M

#475 update tools
  Dockerfile
Labels: size/XS
