Repository helm/chart-testing, pull requests merged in 2022-04, with the labels that each got.

#396 introduce `helm-dependency-extra-args`
  ct/cmd/root.go
  doc/ct.md
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  doc/ct_version.md
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/config/config.go
  pkg/tool/helm.go
Labels: size/L

#428 update Go to 1.18 and kind to 0.12.0
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  examples/kind/test/e2e-kind.sh
  go.mod
  go.sum
Labels: size/S

#429 refactor setup tools
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  setup.sh
  tools/tools.go
Labels: size/M
