Repository helm/chart-testing, pull requests merged in 2023-11, with the labels that each got.

#605 add helm lint extra args
  .github/workflows/ci.yaml
  ct/cmd/root.go
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  pkg/chart/chart.go
  pkg/chart/integration_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_config.json
  pkg/config/test_config.yaml
  pkg/tool/helm.go
Labels: size/M

#606 add stale action
  .github/workflows/stale.yaml
Labels: size/S

#510 (Breaking change) chore: change default target-branch to main
  code-of-conduct.md
  ct/cmd/root.go
  doc/ct_install.md
  doc/ct_lint-and-install.md
  doc/ct_lint.md
  doc/ct_list-changed.md
  examples/kind/README.md
Labels: size/S, Stale
