Repository helm/chart-testing, pull requests merged in 2023-03, with the labels that each got.

#534 Bump tools (helm and kubectl) in Dockerfile
  Dockerfile
Labels: size/XS

#533 Bump tools (yamllint and yamale) from pypi in Dockerfile
  Dockerfile
Labels: size/XS

#527 Update docs and examples for v3.7.1
  README.md
  examples/docker-for-mac/my_test.sh
  examples/gke/Dockerfile
  examples/kind/.circleci/config.yml
  examples/kind/test/e2e-kind.sh
Labels: size/S

#538 sync version comments, update actions and update cosign flag
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .golangci.yml
  .goreleaser.yml
  ct/cmd/docGen.go
  ct/cmd/install.go
  ct/cmd/lint.go
  ct/cmd/lintAndInstall.go
  ct/cmd/listChanged.go
  ct/cmd/version.go
  pkg/chart/chart.go
  pkg/tool/helm.go
Labels: size/M

#539 update goreleaser flags
  .goreleaser.yml
  build.sh
Labels: size/XS
